openapi: 3.0.0

info:
  title: Fractal Machine API
  description: API used to store and retrieve images in S3
  version: 0.0.0

paths:
  /:
    get:
      summary: Returns a list of images.
      description: Returns name of all images in the bucket
      responses:
        '200':
          description: A JSON array of image names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /{image_name}:
    get:
      summary: Returns the image with the given name or 404
      parameters:
        - name: image_name
          in: path
          required: true
          description: The name of the image to retrieve from S3
          schema:
            type: string
      responses:
        '200':
          description: Image found!
        '404':
          description: Image could not be located

